# Generated by Django 3.1.1 on 2021-02-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('brief', models.TextField()),
                ('slogan', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('content_1', models.TextField()),
                ('image_1', models.FileField(upload_to='project/images/')),
                ('content_2', models.TextField()),
                ('image_2', models.FileField(upload_to='project/images/')),
                ('content_3', models.TextField()),
                ('image_3', models.FileField(upload_to='project/images/')),
            ],
        ),
    ]
