# Generated by Django 3.1.1 on 2021-03-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210226_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
